; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Oct 27 2020 10:26:24 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAU7FOP6TSEA:
	dc.w DATAU7FOP6TSEA_0-DATAU7FOP6TSEA, DATAU7FOP6TSEA_1-DATAU7FOP6TSEA
	dc.w DATAU7FOP6TSEA_2-DATAU7FOP6TSEA, DATAU7FOP6TSEA_3-DATAU7FOP6TSEA
DATAU7FOP6TSEA_0: dc.b $A
	dc.b $80, $D, $80, $0, $0
	dc.b $80, $D, $80, $18, $20
	dc.b $80, $D, $80, $20, $40
	dc.b $90, $D, $80, $10, $0
	dc.b $90, $D, $80, $28, $28
	dc.b $A0, $D, $80, $8, $0
	dc.b $A1, $1, $80, $0, $20
	dc.b $A0, $9, $80, $30, $30
	dc.b $40, $5, $81, $A, $0
	dc.b $40, $D, $81, $E, $10
DATAU7FOP6TSEA_1: dc.b $A
	dc.b $80, $D, $80, $0, $0
	dc.b $80, $D, $80, $18, $20
	dc.b $80, $D, $80, $20, $40
	dc.b $90, $D, $80, $10, $0
	dc.b $90, $D, $80, $28, $28
	dc.b $A0, $D, $A0, $8, $0
	dc.b $A1, $1, $A0, $0, $20
	dc.b $A0, $9, $80, $30, $30
	dc.b $40, $5, $81, $A, $0
	dc.b $40, $D, $81, $E, $10
DATAU7FOP6TSEA_2: dc.b $A
	dc.b $80, $D, $80, $0, $0
	dc.b $80, $D, $80, $18, $20
	dc.b $80, $D, $80, $20, $40
	dc.b $90, $D, $A0, $10, $0
	dc.b $90, $D, $80, $28, $28
	dc.b $A0, $D, $80, $8, $0
	dc.b $A1, $1, $80, $0, $20
	dc.b $A0, $9, $80, $30, $30
	dc.b $40, $5, $81, $A, $0
	dc.b $40, $D, $81, $E, $10
DATAU7FOP6TSEA_3: dc.b $A
	dc.b $80, $D, $80, $0, $0
	dc.b $80, $D, $80, $18, $20
	dc.b $80, $D, $80, $20, $40
	dc.b $90, $D, $A0, $10, $0
	dc.b $90, $D, $80, $28, $28
	dc.b $A0, $D, $A0, $8, $0
	dc.b $A1, $1, $A0, $0, $20
	dc.b $A0, $9, $80, $30, $30
	dc.b $40, $5, $81, $A, $0
	dc.b $40, $D, $81, $E, $10
	even