; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Oct 28 2020 10:52:10 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAXK38TOSDYTG:
	dc.w $0, DATAXK38TOSDYTG_1-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_2-DATAXK38TOSDYTG, DATAXK38TOSDYTG_3-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_4-DATAXK38TOSDYTG, DATAXK38TOSDYTG_5-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_6-DATAXK38TOSDYTG, DATAXK38TOSDYTG_7-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_8-DATAXK38TOSDYTG, DATAXK38TOSDYTG_9-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_A-DATAXK38TOSDYTG, DATAXK38TOSDYTG_B-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_C-DATAXK38TOSDYTG, DATAXK38TOSDYTG_D-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_E-DATAXK38TOSDYTG, DATAXK38TOSDYTG_F-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_10-DATAXK38TOSDYTG, DATAXK38TOSDYTG_11-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_12-DATAXK38TOSDYTG, DATAXK38TOSDYTG_13-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_14-DATAXK38TOSDYTG, DATAXK38TOSDYTG_15-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_16-DATAXK38TOSDYTG, DATAXK38TOSDYTG_17-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_18-DATAXK38TOSDYTG, DATAXK38TOSDYTG_19-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_1A-DATAXK38TOSDYTG, DATAXK38TOSDYTG_1B-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_1C-DATAXK38TOSDYTG, DATAXK38TOSDYTG_1D-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_1E-DATAXK38TOSDYTG, DATAXK38TOSDYTG_1F-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_20-DATAXK38TOSDYTG, DATAXK38TOSDYTG_21-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_22-DATAXK38TOSDYTG, DATAXK38TOSDYTG_23-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_24-DATAXK38TOSDYTG, DATAXK38TOSDYTG_25-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_26-DATAXK38TOSDYTG, DATAXK38TOSDYTG_27-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_28-DATAXK38TOSDYTG, DATAXK38TOSDYTG_29-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_2A-DATAXK38TOSDYTG, DATAXK38TOSDYTG_2B-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_2C-DATAXK38TOSDYTG, DATAXK38TOSDYTG_2D-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_2E-DATAXK38TOSDYTG, DATAXK38TOSDYTG_2F-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_30-DATAXK38TOSDYTG, DATAXK38TOSDYTG_31-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_32-DATAXK38TOSDYTG, DATAXK38TOSDYTG_33-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_34-DATAXK38TOSDYTG, DATAXK38TOSDYTG_35-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_36-DATAXK38TOSDYTG, DATAXK38TOSDYTG_37-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_38-DATAXK38TOSDYTG, DATAXK38TOSDYTG_39-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_3A-DATAXK38TOSDYTG, DATAXK38TOSDYTG_3B-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_3C-DATAXK38TOSDYTG, DATAXK38TOSDYTG_3D-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_3E-DATAXK38TOSDYTG, DATAXK38TOSDYTG_3F-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_40-DATAXK38TOSDYTG, DATAXK38TOSDYTG_41-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_42-DATAXK38TOSDYTG, DATAXK38TOSDYTG_43-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_44-DATAXK38TOSDYTG, DATAXK38TOSDYTG_45-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_46-DATAXK38TOSDYTG, DATAXK38TOSDYTG_47-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_48-DATAXK38TOSDYTG, DATAXK38TOSDYTG_49-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_4A-DATAXK38TOSDYTG, DATAXK38TOSDYTG_4B-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_4C-DATAXK38TOSDYTG, DATAXK38TOSDYTG_4D-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_4E-DATAXK38TOSDYTG, DATAXK38TOSDYTG_4F-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_50-DATAXK38TOSDYTG, DATAXK38TOSDYTG_51-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_52-DATAXK38TOSDYTG, DATAXK38TOSDYTG_53-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_54-DATAXK38TOSDYTG, DATAXK38TOSDYTG_55-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_56-DATAXK38TOSDYTG, DATAXK38TOSDYTG_57-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_58-DATAXK38TOSDYTG, DATAXK38TOSDYTG_59-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_5A-DATAXK38TOSDYTG, DATAXK38TOSDYTG_5B-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_5C-DATAXK38TOSDYTG, DATAXK38TOSDYTG_5D-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_5E-DATAXK38TOSDYTG, DATAXK38TOSDYTG_5F-DATAXK38TOSDYTG
	dc.w DATAXK38TOSDYTG_60-DATAXK38TOSDYTG
DATAXK38TOSDYTG_1: dc.b $2
	dc.b $EE, $B, $0, $0, $F4
	dc.b $E, $C, $0, $C, $F4
DATAXK38TOSDYTG_2: dc.b $2
	dc.b $EF, $B, $0, $0, $F2
	dc.b $F, $C, $0, $C, $F2
DATAXK38TOSDYTG_3: dc.b $2
	dc.b $EF, $B, $0, $0, $F2
	dc.b $F, $C, $0, $C, $F2
DATAXK38TOSDYTG_4: dc.b $3
	dc.b $EF, $B, $0, $0, $F2
	dc.b $7, $1, $0, $C, $A
	dc.b $F, $8, $0, $E, $F2
DATAXK38TOSDYTG_5: dc.b $2
	dc.b $ED, $B, $0, $0, $F3
	dc.b $D, $C, $0, $C, $F3
DATAXK38TOSDYTG_6: dc.b $3
	dc.b $EE, $B, $0, $0, $F8
	dc.b $F6, $3, $0, $C, $F0
	dc.b $FE, $1, $0, $10, $10
DATAXK38TOSDYTG_7: dc.b $4
	dc.b $EF, $B, $0, $0, $F5
	dc.b $F7, $0, $0, $C, $D
	dc.b $7, $1, $0, $D, $D
	dc.b $F, $8, $0, $F, $F5
DATAXK38TOSDYTG_8: dc.b $2
	dc.b $F0, $B, $0, $0, $F7
	dc.b $10, $4, $0, $C, $F7
DATAXK38TOSDYTG_9: dc.b $5
	dc.b $EE, $B, $0, $0, $F6
	dc.b $FE, $2, $0, $C, $EE
	dc.b $FE, $1, $0, $F, $E
	dc.b $E, $0, $0, $11, $F5
	dc.b $E, $0, $0, $12, $5
DATAXK38TOSDYTG_A: dc.b $3
	dc.b $EF, $B, $0, $0, $F8
	dc.b $FF, $1, $0, $C, $F0
	dc.b $F, $8, $0, $E, $F8
DATAXK38TOSDYTG_B: dc.b $3
	dc.b $F0, $B, $0, $0, $F4
	dc.b $F8, $0, $0, $C, $C
	dc.b $10, $4, $0, $D, $F4
DATAXK38TOSDYTG_C: dc.b $4
	dc.b $ED, $E, $0, $0, $F1
	dc.b $ED, $2, $0, $C, $11
	dc.b $5, $8, $0, $F, $F1
	dc.b $D, $5, $0, $12, $F9
DATAXK38TOSDYTG_D: dc.b $3
	dc.b $EE, $B, $0, $0, $F2
	dc.b $F6, $6, $0, $C, $A
	dc.b $E, $4, $0, $12, $FA
DATAXK38TOSDYTG_E: dc.b $3
	dc.b $ED, $B, $0, $0, $F5
	dc.b $FD, $2, $0, $C, $D
	dc.b $D, $4, $0, $F, $FD
DATAXK38TOSDYTG_F: dc.b $4
	dc.b $EC, $B, $0, $0, $F3
	dc.b $F4, $1, $0, $C, $B
	dc.b $C, $8, $0, $E, $F3
	dc.b $14, $4, $0, $11, $FB
DATAXK38TOSDYTG_10: dc.b $4
	dc.b $ED, $A, $0, $0, $F4
	dc.b $FD, $2, $0, $9, $C
	dc.b $5, $4, $0, $C, $FC
	dc.b $D, $0, $0, $E, $FC
DATAXK38TOSDYTG_11: dc.b $3
	dc.b $EF, $A, $0, $0, $F3
	dc.b $FF, $4, $0, $9, $B
	dc.b $7, $9, $0, $B, $FB
DATAXK38TOSDYTG_12: dc.b $3
	dc.b $ED, $F, $0, $0, $EE
	dc.b $5, $1, $0, $10, $E
	dc.b $D, $4, $0, $12, $FE
DATAXK38TOSDYTG_13: dc.b $3
	dc.b $ED, $7, $0, $0, $EF
	dc.b $ED, $7, $0, $8, $7
	dc.b $F5, $2, $0, $10, $FF
DATAXK38TOSDYTG_14: dc.b $2
	dc.b $F3, $E, $0, $0, $F0
	dc.b $FB, $1, $0, $C, $10
DATAXK38TOSDYTG_15: dc.b $4
	dc.b $EE, $F, $0, $0, $EE
	dc.b $EE, $1, $0, $10, $E
	dc.b $6, $0, $0, $12, $E
	dc.b $E, $0, $0, $13, $FE
DATAXK38TOSDYTG_16: dc.b $3
	dc.b $F3, $E, $0, $0, $EF
	dc.b $F3, $1, $0, $C, $F
	dc.b $B, $4, $0, $E, $FF
DATAXK38TOSDYTG_17: dc.b $3
	dc.b $F1, $E, $0, $0, $F0
	dc.b $F9, $2, $0, $C, $10
	dc.b $9, $8, $0, $F, $F8
DATAXK38TOSDYTG_18: dc.b $5
	dc.b $ED, $B, $0, $0, $ED
	dc.b $F5, $5, $0, $C, $5
	dc.b $FD, $0, $0, $10, $15
	dc.b $5, $0, $0, $11, $5
	dc.b $D, $8, $0, $12, $ED
DATAXK38TOSDYTG_19: dc.b $4
	dc.b $E9, $B, $0, $0, $F6
	dc.b $F1, $3, $0, $C, $EE
	dc.b $F1, $1, $0, $10, $E
	dc.b $9, $4, $0, $12, $F6
DATAXK38TOSDYTG_1A: dc.b $3
	dc.b $ED, $9, $0, $0, $FD
	dc.b $F5, $6, $0, $6, $ED
	dc.b $FD, $5, $0, $C, $FD
DATAXK38TOSDYTG_1B: dc.b $4
	dc.b $ED, $7, $0, $0, $F4
	dc.b $F5, $2, $0, $8, $EC
	dc.b $F5, $9, $0, $B, $4
	dc.b $5, $4, $0, $11, $4
DATAXK38TOSDYTG_1C: dc.b $4
	dc.b $ED, $8, $0, $0, $FD
	dc.b $F5, $D, $0, $3, $ED
	dc.b $FD, $0, $0, $B, $D
	dc.b $5, $8, $0, $C, $ED
DATAXK38TOSDYTG_1D: dc.b $4
	dc.b $EB, $A, $0, $0, $FF
	dc.b $F3, $7, $0, $9, $EF
	dc.b $3, $4, $0, $11, $FF
	dc.b $B, $0, $0, $13, $FF
DATAXK38TOSDYTG_1E: dc.b $3
	dc.b $F2, $B, $0, $0, $F6
	dc.b $FA, $3, $0, $C, $EE
	dc.b $12, $4, $0, $10, $F6
DATAXK38TOSDYTG_1F: dc.b $3
	dc.b $F1, $B, $0, $0, $F6
	dc.b $F9, $3, $0, $C, $EE
	dc.b $11, $4, $0, $10, $F6
DATAXK38TOSDYTG_20: dc.b $3
	dc.b $F2, $B, $0, $0, $F6
	dc.b $FA, $3, $0, $C, $EE
	dc.b $12, $4, $0, $10, $F6
DATAXK38TOSDYTG_21: dc.b $3
	dc.b $F1, $B, $0, $0, $F6
	dc.b $F9, $3, $0, $C, $EE
	dc.b $11, $4, $0, $10, $F6
DATAXK38TOSDYTG_22: dc.b $3
	dc.b $F0, $B, $0, $0, $F5
	dc.b $F8, $3, $0, $C, $D
	dc.b $10, $8, $0, $10, $F5
DATAXK38TOSDYTG_23: dc.b $3
	dc.b $EF, $B, $0, $0, $F5
	dc.b $F7, $3, $0, $C, $D
	dc.b $F, $8, $0, $10, $F5
DATAXK38TOSDYTG_24: dc.b $3
	dc.b $F0, $B, $0, $0, $F5
	dc.b $F8, $3, $0, $C, $D
	dc.b $10, $4, $0, $10, $FD
DATAXK38TOSDYTG_25: dc.b $3
	dc.b $EF, $B, $0, $0, $F5
	dc.b $F7, $3, $0, $C, $D
	dc.b $F, $8, $0, $10, $F5
DATAXK38TOSDYTG_26: dc.b $3
	dc.b $F2, $E, $0, $0, $F2
	dc.b $FA, $2, $0, $C, $12
	dc.b $A, $8, $0, $F, $FA
DATAXK38TOSDYTG_27: dc.b $3
	dc.b $F2, $E, $0, $0, $F1
	dc.b $FA, $2, $0, $C, $11
	dc.b $A, $8, $0, $F, $F9
DATAXK38TOSDYTG_28: dc.b $3
	dc.b $F2, $E, $0, $0, $F2
	dc.b $FA, $2, $0, $C, $12
	dc.b $A, $8, $0, $F, $FA
DATAXK38TOSDYTG_29: dc.b $3
	dc.b $F2, $E, $0, $0, $F1
	dc.b $FA, $2, $0, $C, $11
	dc.b $A, $8, $0, $F, $F9
DATAXK38TOSDYTG_2A: dc.b $2
	dc.b $EB, $F, $0, $0, $F8
	dc.b $F3, $2, $0, $10, $F0
DATAXK38TOSDYTG_2B: dc.b $2
	dc.b $EB, $F, $0, $0, $F7
	dc.b $F3, $2, $0, $10, $EF
DATAXK38TOSDYTG_2C: dc.b $3
	dc.b $EC, $E, $0, $0, $F8
	dc.b $F4, $2, $0, $C, $F0
	dc.b $4, $8, $0, $F, $F8
DATAXK38TOSDYTG_2D: dc.b $2
	dc.b $EB, $F, $0, $0, $F7
	dc.b $F3, $2, $0, $10, $EF
DATAXK38TOSDYTG_2E: dc.b $2
	dc.b $F3, $B, $0, $0, $F3
	dc.b $FB, $1, $0, $C, $B
DATAXK38TOSDYTG_2F: dc.b $2
	dc.b $F3, $E, $0, $0, $F3
	dc.b $B, $4, $0, $C, $F3
DATAXK38TOSDYTG_30: dc.b $2
	dc.b $F3, $E, $0, $0, $F3
	dc.b $B, $8, $0, $C, $F3
DATAXK38TOSDYTG_31: dc.b $2
	dc.b $F3, $E, $0, $0, $F3
	dc.b $B, $8, $0, $C, $F3
DATAXK38TOSDYTG_32: dc.b $2
	dc.b $F3, $E, $0, $0, $F3
	dc.b $B, $8, $0, $C, $F3
DATAXK38TOSDYTG_33: dc.b $2
	dc.b $F5, $E, $0, $0, $EC
	dc.b $F5, $2, $0, $C, $C
DATAXK38TOSDYTG_34: dc.b $3
	dc.b $F0, $A, $0, $0, $F8
	dc.b $F8, $2, $0, $9, $F0
	dc.b $8, $4, $0, $C, $F8
DATAXK38TOSDYTG_35: dc.b $2
	dc.b $EC, $B, $0, $0, $F5
	dc.b $C, $8, $0, $C, $F5
DATAXK38TOSDYTG_36: dc.b $3
	dc.b $F0, $A, $0, $0, $F0
	dc.b $F8, $2, $0, $9, $8
	dc.b $8, $4, $0, $C, $F8
DATAXK38TOSDYTG_37: dc.b $3
	dc.b $F6, $A, $0, $0, $F3
	dc.b $6, $1, $0, $9, $B
	dc.b $E, $4, $0, $B, $FB
DATAXK38TOSDYTG_38: dc.b $3
	dc.b $F2, $A, $0, $0, $F0
	dc.b $FA, $3, $0, $9, $8
	dc.b $A, $0, $0, $D, $0
DATAXK38TOSDYTG_39: dc.b $2
	dc.b $FB, $E, $0, $0, $F1
	dc.b $13, $8, $0, $C, $F1
DATAXK38TOSDYTG_3A: dc.b $4
	dc.b $EC, $B, $0, $0, $E5
	dc.b $F4, $4, $0, $C, $FD
	dc.b $FC, $0, $0, $E, $FD
	dc.b $C, $8, $0, $F, $E5
DATAXK38TOSDYTG_3B: dc.b $3
	dc.b $EC, $D, $0, $0, $E5
	dc.b $FC, $A, $0, $8, $E5
	dc.b $4, $0, $0, $11, $FD
DATAXK38TOSDYTG_3C: dc.b $4
	dc.b $F4, $D, $0, $0, $F8
	dc.b $F4, $1, $0, $8, $18
	dc.b $FC, $1, $0, $A, $F0
	dc.b $4, $8, $0, $C, $F8
DATAXK38TOSDYTG_3D: dc.b $3
	dc.b $F4, $D, $0, $0, $EA
	dc.b $F4, $5, $0, $8, $A
	dc.b $4, $C, $0, $C, $F2
DATAXK38TOSDYTG_3E: dc.b $3
	dc.b $F5, $D, $0, $0, $E5
	dc.b $FD, $1, $0, $8, $5
	dc.b $5, $8, $0, $A, $ED
DATAXK38TOSDYTG_3F: dc.b $4
	dc.b $F5, $D, $0, $0, $F8
	dc.b $F5, $1, $0, $8, $18
	dc.b $FD, $1, $0, $A, $F0
	dc.b $5, $8, $0, $C, $F8
DATAXK38TOSDYTG_40: dc.b $2
	dc.b $E9, $B, $0, $0, $F3
	dc.b $9, $5, $0, $C, $F3
DATAXK38TOSDYTG_41: dc.b $2
	dc.b $F8, $E, $0, $0, $EC
	dc.b $0, $1, $0, $C, $C
DATAXK38TOSDYTG_42: dc.b $2
	dc.b $F8, $E, $0, $0, $EB
	dc.b $0, $1, $0, $C, $B
DATAXK38TOSDYTG_43: dc.b $4
	dc.b $E9, $F, $0, $0, $F0
	dc.b $F1, $1, $0, $10, $10
	dc.b $9, $8, $0, $12, $F8
	dc.b $11, $4, $0, $15, $F8
DATAXK38TOSDYTG_44: dc.b $4
	dc.b $E8, $F, $0, $0, $F0
	dc.b $E8, $1, $0, $10, $10
	dc.b $8, $8, $0, $12, $F8
	dc.b $10, $4, $0, $15, $F8
DATAXK38TOSDYTG_45: dc.b $2
	dc.b $F0, $F, $0, $0, $EE
	dc.b $10, $C, $0, $10, $EE
DATAXK38TOSDYTG_46: dc.b $2
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $4, $0, $C, $F3
DATAXK38TOSDYTG_47: dc.b $2
	dc.b $F0, $F, $0, $0, $EF
	dc.b $10, $8, $0, $10, $EF
DATAXK38TOSDYTG_48: dc.b $2
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $4, $0, $C, $F3
DATAXK38TOSDYTG_49: dc.b $3
	dc.b $EE, $B, $0, $0, $F3
	dc.b $F6, $3, $0, $C, $B
	dc.b $E, $8, $0, $10, $F3
DATAXK38TOSDYTG_4A: dc.b $3
	dc.b $EB, $B, $0, $0, $F2
	dc.b $B, $8, $0, $C, $F2
	dc.b $13, $4, $0, $F, $FA
DATAXK38TOSDYTG_4B: dc.b $5
	dc.b $EA, $D, $0, $0, $F4
	dc.b $EA, $1, $0, $8, $14
	dc.b $FA, $A, $0, $A, $F4
	dc.b $2, $1, $0, $13, $C
	dc.b $12, $0, $0, $15, $F4
DATAXK38TOSDYTG_4C: dc.b $5
	dc.b $E9, $D, $0, $0, $F4
	dc.b $E9, $1, $0, $8, $14
	dc.b $F9, $A, $0, $A, $F4
	dc.b $9, $0, $0, $13, $C
	dc.b $11, $0, $0, $14, $F4
DATAXK38TOSDYTG_4D: dc.b $5
	dc.b $EA, $D, $0, $0, $F4
	dc.b $EA, $1, $0, $8, $14
	dc.b $FA, $A, $0, $A, $F4
	dc.b $2, $1, $0, $13, $C
	dc.b $12, $0, $0, $15, $F4
DATAXK38TOSDYTG_4E: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $F4, $3, $0, $C, $8
	dc.b $C, $8, $0, $10, $F0
DATAXK38TOSDYTG_4F: dc.b $3
	dc.b $EE, $B, $0, $0, $F2
	dc.b $F6, $2, $0, $C, $A
	dc.b $E, $8, $0, $F, $F2
DATAXK38TOSDYTG_50: dc.b $2
	dc.b $F2, $7, $0, $0, $F5
	dc.b $FA, $2, $0, $8, $5
DATAXK38TOSDYTG_51: dc.b $1
	dc.b $F7, $6, $0, $0, $F9
DATAXK38TOSDYTG_52: dc.b $1
	dc.b $FB, $1, $0, $0, $FC
DATAXK38TOSDYTG_53: dc.b $4
	dc.b $F4, $D, $0, $0, $E4
	dc.b $F4, $2, $0, $8, $4
	dc.b $FC, $1, $0, $B, $C
	dc.b $4, $8, $0, $D, $EC
DATAXK38TOSDYTG_54: dc.b $3
	dc.b $F5, $D, $0, $0, $FC
	dc.b $FD, $1, $0, $8, $F4
	dc.b $5, $8, $0, $A, $FC
DATAXK38TOSDYTG_55: dc.b $3
	dc.b $F3, $E, $0, $0, $EC
	dc.b $F3, $3, $0, $C, $C
	dc.b $B, $8, $0, $10, $F4
DATAXK38TOSDYTG_56: dc.b $4
	dc.b $EE, $F, $0, $0, $EE
	dc.b $FE, $1, $0, $10, $E
	dc.b $E, $4, $0, $12, $EE
	dc.b $E, $0, $0, $14, $6
DATAXK38TOSDYTG_57: dc.b $3
	dc.b $F3, $E, $0, $0, $EC
	dc.b $F3, $3, $0, $C, $C
	dc.b $B, $8, $0, $10, $F4
DATAXK38TOSDYTG_58: dc.b $2
	dc.b $F8, $E, $0, $0, $F0
	dc.b $10, $8, $0, $C, $F0
DATAXK38TOSDYTG_59: dc.b $2
	dc.b $F8, $E, $0, $0, $F0
	dc.b $10, $8, $0, $C, $F0
DATAXK38TOSDYTG_5A: dc.b $2
	dc.b $F8, $E, $0, $0, $F0
	dc.b $10, $8, $0, $C, $F0
DATAXK38TOSDYTG_5B: dc.b $2
	dc.b $F8, $E, $0, $0, $F0
	dc.b $10, $8, $0, $C, $F0
DATAXK38TOSDYTG_5C: dc.b $2
	dc.b $F8, $E, $0, $0, $F0
	dc.b $10, $8, $0, $C, $F0
DATAXK38TOSDYTG_5D: dc.b $2
	dc.b $F8, $E, $0, $0, $F0
	dc.b $10, $8, $0, $C, $F0
DATAXK38TOSDYTG_5E: dc.b $2
	dc.b $F0, $B, $0, $0, $F0
	dc.b $F8, $2, $0, $C, $8
DATAXK38TOSDYTG_5F: dc.b $4
	dc.b $6, $C, $0, $0, $EC
	dc.b $F6, $9, $0, $4, $F4
	dc.b $E, $8, $0, $A, $FC
	dc.b $6, $0, $0, $D, $C
DATAXK38TOSDYTG_60: dc.b $3
	dc.b $5, $D, $0, $0, $EC
	dc.b $F5, $9, $0, $8, $F4
	dc.b $5, $1, $0, $E, $C
	even